import { Octokit } from "@octokit/rest";
import type { GeneratedFile } from "@/types/saaya";

/**
 * Creates a branch, commits all generated .saaya/repowiki/ files, and opens a PR
 */
export async function createSaayaPullRequest({
  githubToken,
  owner,
  repo,
  saayaFiles,
}: {
  githubToken: string;
  owner: string;
  repo: string;
  saayaFiles: GeneratedFile[];
}): Promise<string> {
  const octokit = new Octokit({ auth: githubToken });

  // 1. Get default branch & latest commit SHA
  const { data: repoData } = await octokit.repos.get({ owner, repo });
  const defaultBranch = repoData.default_branch;
  const { data: refData } = await octokit.git.getRef({
    owner,
    repo,
    ref: `heads/${defaultBranch}`,
  });
  const latestCommitSha = refData.object.sha;

  // 2. Create Branch `docs/saaya-repowiki-[timestamp]`
  const branchName = `docs/saaya-repowiki-${Date.now()}`;
  await octokit.git.createRef({
    owner,
    repo,
    ref: `refs/heads/${branchName}`,
    sha: latestCommitSha,
  });

  // 3. Create Tree Items for `.saaya/repowiki/...`
  const treeItems = saayaFiles.map((file) => ({
    path: `.saaya/repowiki/${file.path}`,
    mode: "100644" as const,
    type: "blob" as const,
    content: file.content,
  }));

  const { data: treeData } = await octokit.git.createTree({
    owner,
    repo,
    base_tree: latestCommitSha,
    tree: treeItems,
  });

  // 4. Create Commit
  const { data: commitData } = await octokit.git.createCommit({
    owner,
    repo,
    message:
      "docs(saaya): generate comprehensive RepoWiki knowledge base [skip ci]",
    tree: treeData.sha,
    parents: [latestCommitSha],
  });

  // 5. Update Branch Ref
  await octokit.git.updateRef({
    owner,
    repo,
    ref: `heads/${branchName}`,
    sha: commitData.sha,
  });

  // 6. Create Pull Request
  const { data: prData } = await octokit.pulls.create({
    owner,
    repo,
    title: "🛡️ Add Auto-Generated Saaya RepoWiki Knowledge Base",
    head: branchName,
    base: defaultBranch,
    body: `## 🛡️ Saaya RepoWiki Documentation

This PR introduces a comprehensive, pre-indexed knowledge base and architectural documentation suite generated under \`.saaya/repowiki/\`.

### Included Documentation:
- 🏗️ **System Architecture & Tech Stack Matrix**
- 🔌 **Backend & Frontend API Specifications**
- ⚡ **Background Workers & Async Queue Pipelines**
- 🗄️ **Database Schemas & Migrations**
- 📦 **Shared Package Documentation**
- 📖 **Getting Started & Contributing Guides**
- 🧩 **Modular Code Knowledge Cards (\`knowledge/en/\`)**

### Structure:
\`\`\`
.saaya/repowiki/
├── en/content/          # Human-readable articles with citations & Mermaid diagrams
├── en/meta/             # repowiki-metadata.json (knowledge graph)
└── knowledge/en/        # 6-file module cards + standalone tech cards
\`\`\`

---
*Generated by [Saaya](https://github.com/repo-saaya) — AI Repository Knowledge Generator*`,
  });

  return prData.html_url;
}
